

-- Keys for the CSK_META saved variable array
CSK_SHOW_WHISPER_WARNING			= 'CSK_SHOW_WHISPER_WARNING'
CSK_LAST_SEEN_MESSAGE_VERSION		= 'CSK_LAST_SEEN_MESSAGE_VERSION'

-- Keys for the CSK_PREFS saved variable array
CSK_PREFS_DEBUG							= 'CSK_DEBUG'
CSK_PREFS_NEVER_OFFER_BOE				= 'CSK_NEVER_OFFER_BOE'
CSK_PREFS_CURRENT_SPEC_ONLY				= 'CSK_CURRENT_SPEC_ONLY'
CSK_PREFS_ILVL_THRESHOLD				= 'CSK_ILVL_THRESHOLD'
CSK_PREFS_WHISPER_MESSAGE				= 'CSK_WHISPER_MESSAGE'
CSK_PREFS_SHOW_TRADEABLE_ALERT			= 'CSK_SHOW_TRADEABLE_ALERT'
CSK_PREFS_ANNOUNCE_TRADES				= 'CSK_ANNOUNCE_TRADES'

-- Default values for CSK_PREFS saved variable array
CSK_DEFAULT_PREFS = {
	[CSK_PREFS_DEBUG]					= false,
	[CSK_PREFS_NEVER_OFFER_BOE]			= false,
	[CSK_PREFS_CURRENT_SPEC_ONLY]		= false,
	[CSK_PREFS_SHOW_TRADEABLE_ALERT]	= true,
	[CSK_PREFS_ANNOUNCE_TRADES]			= false
}

-- Roles
CSK_ROLE_AGILITY_DPS				= 'AGILITY_DPS'
CSK_ROLE_INTELLECT_DPS				= 'INTELLECT_DPS'
CSK_ROLE_STRENGTH_DPS				= 'STRENGTH_DPS'
CSK_ROLE_HEALER						= 'HEALER'
CSK_ROLE_TANK						= 'TANK'
CSK_ROLE_UNKNOWN					= 'UNKNOWN'
